[package]
name = "btleplug"
version = "0.4.0"
authors = ["Nonpolynomial <kyle@nonpolynomial.com>"]
license = "MIT/Apache-2.0/BSD-3-Clause"
repository = "https://github.com/deviceplug/btleplug"
homepage = "https://github.com/deviceplug/btleplug"
edition = "2018"
description = """
A Cross-Platform Rust Bluetooth Low Energy (BLE) GATT
library.
"""

readme = "README.md"
keywords = ["bluetooth", "BLE", "bluez", "uwp", "corebluetooth"]
categories = ["hardware-support"]

[lib]
name = "btleplug"
path = "src/lib.rs"
# crate-type = ["staticlib"]

[dependencies]
libc = "0.2.45"
nix = "0.12.0"
bytes = "0.4"
num = "0.1.41"
log = "0.3.8"
enum_primitive = "0.1.1"
bitflags = "1.0.1"
failure = "0.1.1"
failure_derive = "0.1.1"
backtrace = "0.3.5"
cocoa = "0.20.0"
objc = "0.2"
async-std = { version = "1.4.0", features = ["unstable"] }
uuid = "0.8.1"
crossbeam = "0.7.3"

[dependencies.nom]
version = "^4.0"
features = ["verbose-errors"]

[dependencies.winrt]
version = "0.6.0"
features = ["windows-devices", "windows-storage"]

[target.'cfg(macos)'.dependencies]
objc = "0.2"
cocoa = "0.20.0"

[target.'cfg(ios)'.dependencies]
objc = "0.2"
cocoa = "0.20.0"

[dev-dependencies]
rand = "0.4.2"
