[package]
name = "btleplug"
version = "0.3.1"
authors = ["Nonpolynomial <kyle@nonpolynomial.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/deviceplug/btleplug"
homepage = "https://github.com/deviceplug/btleplug"

description = """
A Cross-Platform Rust Bluetooth Low Energy (BLE) GATT
library.
"""

readme = "README.md"
keywords = ["bluetooth", "BLE", "IOT", "bluez", "winrt", "corebluetooth"]
categories = ["network-programming", "hardware-support"]

[dependencies]
libc = "0.2.45"
nix = "0.12.0"
bytes = "0.4"
num = "0.1.41"
log = "0.3.8"
enum_primitive = "0.1.1"
bitflags = "1.0.1"
failure = "0.1.1"
failure_derive = "0.1.1"
backtrace = "0.3.5"

[dependencies.nom]
version = "^4.0"
features = ["verbose-errors"]

[dependencies.winrt]
version = "0.6.0"
features = ["windows-devices", "windows-storage"]

[dev-dependencies]
rand = "0.4.2"
