[package]
name = "btleplug"
version = "0.6.0"
authors = ["Nonpolynomial, LLC <kyle@nonpolynomial.com>"]
license = "MIT/Apache-2.0/BSD-3-Clause"
repository = "https://github.com/deviceplug/btleplug"
homepage = "https://github.com/deviceplug/btleplug"
edition = "2018"
description = """
A Cross-Platform Rust Bluetooth Low Energy (BLE) GATT
library.
"""

readme = "README.md"
keywords = ["bluetooth", "BLE", "bluez", "uwp", "corebluetooth"]
categories = ["hardware-support"]

[lib]
name = "btleplug"
path = "src/lib.rs"
# crate-type = ["staticlib"]

[features]
serde = ["uuid/serde", "serde_cr"]

[dependencies]
log = "0.4.14"
bitflags = "1.2.1"
thiserror = "1.0"
uuid = "0.8.2"
serde_cr = { package = "serde", version = "1.0.123", features = ["derive"], default-features = false, optional = true }
dashmap = "4.0.2"
futures = "0.3.12"

[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.9.1"
displaydoc = "0.1.7"
parking_lot = "0.11.1"
static_assertions = "1.1.0"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
async-std = "1.9.0"
cocoa = "0.24.0"
objc = "0.2.7"
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = "0.3.1"

[target.'cfg(target_os = "windows")'.build-dependencies]
windows = "0.3.1"

[dev-dependencies]
simple_logger = "1.11.0"
rand = "0.8.3"

# The build script uses `dbus-codegen` to generate BlueZ's DBus traits for use in the linux library.
# The `build.rs` file does nothing on other platforms.
[build-dependencies.dbus-codegen]
version = "0.9.1"
# Disable the default feature which requires the DBus C API to be installed.
default-features = false
