[package]
name = "btleplug"
version = "0.8.0"
authors = ["Nonpolynomial, LLC <kyle@nonpolynomial.com>"]
license = "MIT/Apache-2.0/BSD-3-Clause"
repository = "https://github.com/deviceplug/btleplug"
homepage = "https://github.com/deviceplug/btleplug"
edition = "2018"
description = """
A Cross-Platform Rust Bluetooth Low Energy (BLE) GATT
library.
"""

readme = "README.md"
keywords = ["bluetooth", "BLE", "bluez", "uwp", "corebluetooth"]
categories = ["hardware-support"]

[lib]
name = "btleplug"
path = "src/lib.rs"
# crate-type = ["staticlib"]

[features]
serde = ["uuid/serde", "serde_cr", "serde_bytes"]

[dependencies]
async-trait = "0.1.50"
log = "0.4.14"
bitflags = "1.2.1"
thiserror = "1.0.26"
uuid = "0.8.2"
serde_cr = { package = "serde", version = "1.0.126", features = ["derive"], default-features = false, optional = true }
serde_bytes = { version = "0.11.5", optional = true }
dashmap = "4.0.2"
futures = "0.3.16"
static_assertions = "1.1.0"
tokio = { version = "1.9.0", features = ["rt", "sync"] }
tokio-stream = { version = "0.1", features = ["sync"]}

[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.9.3"
displaydoc = "0.2.3"
parking_lot = "0.11.1"
tokio = { version = "1.9.0", features = ["rt"] }
bluez-async = "0.3.1"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
cocoa = "0.24.0"
objc = "0.2.7"
libc = "0.2.98"

[target.'cfg(target_os = "windows")'.dependencies]
tokio = { version = "1.9.0", features = ["rt", "sync"] }
windows = "0.18.0"

[target.'cfg(target_os = "windows")'.build-dependencies]
windows = "0.18.0"

[dev-dependencies]
rand = "0.8.4"
pretty_env_logger = "0.4.0"
tokio = { version = "1.9.0", features = ["macros", "rt", "rt-multi-thread"] }
serde_json = "1.0.64"

