[package]
name = "rumble"
version = "0.2.1"
authors = ["Micah Wylde <micah@micahw.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/mwylde/rumble"
homepage = "https://github.com/mwylde/rumble"

description = """
A Rust Bluetooth Low Energy (BLE) central module
library, currently supporting Linux/Bluez
"""

readme = "README.md"
keywords = ["bluetooth", "BLE", "IOT", "bluez"]
categories = ["network-programming", "hardware-support"]

[dependencies]
libc = "0.2.33"
nix = "0.9.0"
bytes = "0.4"
num = "0.1.41"
log = "0.3.8"
enum_primitive = "0.1.1"
bitflags = "1.0.1"
failure = "0.1.1"
failure_derive = "0.1.1"
backtrace = "0.3.5"

[dependencies.nom]
version = "^4.0"
features = ["verbose-errors"]

[dev-dependencies]
rand = "0.4.2"
