[package]
name = "btleplug"
version = "0.5.5"
authors = ["Nonpolynomial <kyle@nonpolynomial.com>"]
license = "MIT/Apache-2.0/BSD-3-Clause"
repository = "https://github.com/deviceplug/btleplug"
homepage = "https://github.com/deviceplug/btleplug"
edition = "2018"
description = """
A Cross-Platform Rust Bluetooth Low Energy (BLE) GATT
library.
"""

readme = "README.md"
keywords = ["bluetooth", "BLE", "bluez", "uwp", "corebluetooth"]
categories = ["hardware-support"]

[lib]
name = "btleplug"
path = "src/lib.rs"
# crate-type = ["staticlib"]

[dependencies]
libc = "0.2.82"
nix = "0.19.1"
bytes = "1.0.1"
num = "0.3.1"
log = "0.4.13"
enum_primitive = "0.1.1"
bitflags = "1.2.1"
failure = "0.1.8"
failure_derive = "0.1.8"
backtrace = "0.3.55"
async-std = "1.9.0"
uuid = "0.8.2"
serde = { version = "1.0.119", features = ["derive"], default-features = false, optional = true }
dashmap = "4.0.2"
futures = "0.3.12"

[dependencies.nom]
# This is stuck at 4 until we update the bluez core
version = "^4"
features = ["verbose-errors"]

[dependencies.winrt]
# This is stuck at 0.6 until we update the UWP core
version = "^0.6"
features = ["windows-devices", "windows-storage"]

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
cocoa = "0.24.0"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2.7"
cocoa = "0.24.0"

[dev-dependencies]
rand = "0.8.2"
